### ISSUE TITLE
Скрипт для запуска бота в качестве системного сервиса

### ISSUE THREAD

**Issue by DronMDF** [DronMDF/telebot#15]

**Comment by DronMDF** [comment]
@0crat in

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/datum):

```
java.io.IOException: java.lang.IllegalStateException: Failed to acquire "PMO/people.xml" in 20s
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:74)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:60)
	at com.zerocracy.farm.UplinkedProject.acq(UplinkedProject.java:100)
	at com.zerocracy.farm.reactive.RvProject.acq(RvProject.java:61)
	at com.zerocracy.farm.ruled.RdProject.acq(RdProject.java:54)
	at com.zerocracy.pmo.Pmo.acq(Pmo.java:53)
	at com.zerocracy.pmo.People.item(People.java:371)
	at com.zerocracy.pmo.People.bootstrap(People.java:71)
	at com.zerocracy.radars.github.Author.login(Author.java:61)
	at com.zerocracy.radars.github.ReQuestion.react(ReQuestion.java:58)
	at com.zerocracy.radars.github.ReIfAddressed.react(ReIfAddressed.java:58)
	at com.zerocracy.radars.github.ReNotMine.react(ReNotMine.java:55)
	at com.zerocracy.radars.github.ReSafe.lambda$react$0(ReSafe.java:61)
	at org.cactoos.func.FuncWithFallback.apply(FuncWithFallback.java:299)
	at org.c...
```

**Comment by DronMDF** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/DronMDF/telebot/issues/15#issuecomment-333236684))

@DronMDF Job `gh:dronmdf/telebot#15` is in scope.

**Comment by 0crat** [comment]
+15 points just awarded to @dronmdf, total is [+240](http://www.0crat.com/u/dronmdf).

**Comment by 0crat** [comment]
I can't do it for technical reasons, I'm very sorry. If you don't know what to do, submit this error as a ticket [here](https://github.com/zerocracy/datum):

```
1.0-SNAPSHOT 0ead988 2017-09-29T20:23:29
IllegalStateException: java.lang.reflect.InvocationTargetException
java.lang.AssertionError: HTTP response status is not equal to 200:
403 Forbidden [https://api.github.com/repos/dronmdf/telebot/issues/15/comments?since=1970-01-01T00%3A00%3A00Z]
Server: GitHub.com
Date: Fri, 29 Sep 2017 21:42:23 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Status: 403 Forbidden
X-RateLimit-Limit: 5000
X-RateLimit-Remaining: 0
X-RateLimit-Reset: 1506721344
X-GitHub-Media-Type: github.v3
Access-Control-Expose-Headers: ETag, Link, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval
Access-Control-Allow-Origin: *
Content-Security-Policy: default-src 'none'
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-Runtime-Rack: 0.041618
X-GitHub-Request-Id: A9E3:7A69:13DC6C9:32D1F81:59CEBE3F

{"message":"API rate limit exceeded for 0crat.","documentation_url":...
```

**Comment by DronMDF** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/DronMDF/telebot/issues/15#issuecomment-333651399))

@DronMDF Oops! Job `gh:dronmdf/telebot#15` is already in scope

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#15` is now out of scope.

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @pavelonex, total is [+45](http://www.0crat.com/u/pavelonex).
