### ISSUE TITLE
Second work

### ISSUE THREAD

**Issue by DronMDF** [DronMDF/telebot#2]

**Comment by DronMDF** [comment]
@0crat hello
where are you?

**Comment by DronMDF** [comment]
@0crat in

**Comment by DronMDF** [comment]
@0crat in please.

**Comment by 0crat** [comment]
> @0crat in please. ([here](https://github.com/DronMDF/telebot/issues/2#issuecomment-321589570))

@DronMDF Job `gh:dronmdf/telebot#2` is in scope.

**Comment by 0crat** [comment]
+15 points just awarded to @dronmdf, total is [+30](http://www.0crat.com/u/dronmdf).

**Comment by DronMDF** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/DronMDF/telebot/issues/2#issuecomment-321761156))

@DronMDF Job `gh:dronmdf/telebot#2` is now out of scope.

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/DronMDF/telebot/issues/2#issuecomment-321761156))

@DronMDF I can't do it for technical reasons, I'm very sorry. If you don't know what to do, submit this error as a ticket [here](https://github.com/zerocracy/datum):

```
1.0-SNAPSHOT 1cbcae0 2017-08-11T07:54:51
IllegalStateException: java.lang.reflect.InvocationTargetException
java.lang.IllegalStateException: Failed to acquire "2017/08/C6KLDT6QG/orders.xml" in 20s
	at com.zerocracy.farm.sync.SyncItem.acquire(SyncItem.java:92)
	at com.zerocracy.farm.sync.SyncProject.acq(SyncProject.java:134)
	at com.zerocracy.farm.StrictProject.acq(StrictProject.java:107)
	at com.zerocracy.farm.UplinkedProject.lambda$acq$4(UplinkedProject.java:98)
	at org.cactoos.scalar.Ternary.value(Ternary.java:118)
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:66)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:60)
	at com.zerocracy.farm.UplinkedProject.acq(UplinkedProject.java:100)
	at com.zerocracy.pm.in.Orders.item(Orders.java:179)
	at com.zerocracy.pm.in.Orders.bootstrap(Orders.java:58)
	at com.zerocracy.pm.in.Orders$bootstrap.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.run...
```

**Comment by DronMDF** [comment]
@0crat skills
Хочу получить список команд. :)

**Comment by DronMDF** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/DronMDF/telebot/issues/2#issuecomment-321764072))

@DronMDF Job `gh:dronmdf/telebot#2` is in scope.

**Comment by 0crat** [comment]
+15 points just awarded to @dronmdf, total is [+60](http://www.0crat.com/u/dronmdf).

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#2` assigned to @spark, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by roman901** [comment]
@0crat resign

**Comment by 0crat** [comment]
> @0crat resign ([here](https://github.com/DronMDF/telebot/issues/2#issuecomment-323302035))

@roman901 I can't do it for technical reasons, I'm very sorry. If you don't know what to do, submit this error as a ticket [here](https://github.com/zerocracy/datum):

```
1.0-SNAPSHOT af3b6ad 2017-08-17T11:08:29
IllegalStateException: java.lang.reflect.InvocationTargetException
com.zerocracy.jstk.SoftException: You need to have one of these roles in order to do what you're trying to do: ARC, PO. I'm sorry to say this, but at the moment you've got no roles in this project (your GitHub login is "roman901").
	at com.zerocracy.farm.Assume.roles(Assume.java:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoCachedMethodSite.invoke(PojoMetaMethodSite.java:192)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.c...
```

**Comment by roman901** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/DronMDF/telebot/issues/2#issuecomment-323709262))

@roman901 I can't do it for technical reasons, I'm very sorry. If you don't know what to do, submit this error as a ticket [here](https://github.com/zerocracy/datum):

```
1.0-SNAPSHOT 2212f26 2017-08-18T15:01:07
IllegalStateException: java.lang.reflect.InvocationTargetException
com.zerocracy.jstk.SoftException: You need to have one of these roles in order to do what you're trying to do: ARC, PO. I'm sorry to say this, but at the moment you've got no roles in this project (your GitHub login is "roman901").
	at com.zerocracy.farm.Assume.roles(Assume.java:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoCachedMethodSite.invoke(PojoMetaMethodSite.java:192)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.c...
```

**Comment by DronMDF** [comment]
@0crat refuse

Давай я попробую, но странно. Вообще это должен делать DEV.

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#2` is now out of scope.

**Comment by 0crat** [comment]
+30 points just awarded to @spark, total is [+60](http://www.0crat.com/u/spark).
