### ISSUE TITLE
Do it again

### ISSUE THREAD

**Issue by DronMDF** [DronMDF/telebot#4]

**Comment by 0crat** [comment]
@dron please, pay attention to this issue

**Comment by DronMDF** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/DronMDF/telebot/issues/4#issuecomment-322457588))

@DronMDF Job `gh:dronmdf/telebot#4` is in scope.

**Comment by 0crat** [comment]
+15 points just awarded to @dronmdf, total is [+75](http://www.0crat.com/u/dronmdf).

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#4` assigned to @spark, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by roman901** [comment]
@0crat resign

**Comment by 0crat** [comment]
> @0crat resign ([here](https://github.com/DronMDF/telebot/issues/4#issuecomment-322866381))

@roman901 I can't do it for technical reasons, I'm very sorry. If you don't know what to do, submit this error as a ticket [here](https://github.com/zerocracy/datum):

```
1.0-SNAPSHOT f13f15f 2017-08-16T16:27:32
IllegalStateException: java.lang.reflect.InvocationTargetException
com.zerocracy.jstk.SoftException: You need to have one of these roles in order to do what you're trying to do: ARC, PO. I'm sorry to say this, but at the moment you've got no roles in this project (your GitHub login is "roman901").
	at com.zerocracy.farm.Assume.roles(Assume.java:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoCachedMethodSite.invoke(PojoMetaMethodSite.java:192)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.c...
```

**Comment by DronMDF** [comment]
@0crat resign

**Comment by 0crat** [comment]
> @0crat resign ([here](https://github.com/DronMDF/telebot/issues/4#issuecomment-322890398))

@DronMDF @spark resigned from `gh:dronmdf/telebot#4`, please stop working.

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#4` assigned to @spark, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by DronMDF** [comment]
Спасибо, этот запрос считаем закрытым, и 0crat должен выдать +30 поинтов.

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#4` is now out of scope.

**Comment by 0crat** [comment]
+30 points just awarded to @spark, total is [+30](http://www.0crat.com/u/spark).
