### ISSUE TITLE
cpu.py:3-4: Необходимо определить загрузку...

### ISSUE THREAD

**Issue by 0pdd** [DronMDF/telebot#42]
The puzzle `40-5225b520` (from #40) in [`tb/sources/cpu.py`](https://github.com/DronMDF/telebot/blob/master/tb/sources/cpu.py) (lines 3-4) has to be resolved: "Необходимо определить загрузку системы за последнюю минуту. Если загрузка превышает указанный предел - сгенерировать событие."

The puzzle was created by Andrey Valyaev on 10-Oct-17. 

Estimate: 0 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@dronmdf please, pay attention to this issue

**Comment by DronMDF** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/DronMDF/telebot/issues/42#issuecomment-335588754))

@DronMDF Job `gh:dronmdf/telebot#42` is in scope.

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#42` assigned to @pavelonex, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by DronMDF** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/DronMDF/telebot/issues/42#issuecomment-341880625))

@DronMDF @pavelonex resigned from `gh:dronmdf/telebot#42`, since the job is not in scope anymore.

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/DronMDF/telebot/issues/42#issuecomment-341880625))

@DronMDF Job `gh:dronmdf/telebot#42` is now out of scope.

**Comment by 0crat** [comment]
I can't do it for technical reasons, I'm very sorry. If you don't know what to do, submit this error as a ticket [here](https://github.com/zerocracy/datum):

```
1.0-SNAPSHOT 9247df1 2017-12-27T13:42:02
IllegalStateException: java.lang.reflect.InvocationTargetException in com/zerocracy/stk/pm/in/orders/finish_order.groovy
java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException in com/zerocracy/stk/pm/in/orders/finish_order.groovy
	at com.zerocracy.farm.reactive.StkGroovy.process(StkGroovy.java:125)
	at com.zerocracy.farm.StkSafe.process(StkSafe.java:87)
	at com.zerocracy.farm.reactive.StkSmart.process(StkSmart.java:66)
	at com.zerocracy.farm.reactive.Brigade.process(Brigade.java:82)
	at com.zerocracy.farm.reactive.Brigade.lambda$apply$0(Brigade.java:64)
	at org.cactoos.func.UncheckedFunc.lambda$apply$0(UncheckedFunc.java:58)
	at org.cactoos.func.IoCheckedBiFunc.apply(IoCheckedBiFunc.java:66)
	at org.cactoos.func.UncheckedBiFunc.apply(UncheckedBiFunc.java:60)
	at org.cactoos.func.UncheckedFunc.apply(UncheckedFunc.java:59)
	at org.cactoos.iterator.Filtered.hasNext(Filtered.java:90)
	at org.cactoos.iterator.LengthOf.value(LengthOf.java:56)
	at org.cactoos.iterable.LengthOf.value(LengthOf.java:56)
	at com.zerocracy.farm.reactive.Brigade.apply(Brigade.java:67)
	at com.zerocracy.farm.r...
```

Cc @yegor256

**Comment by 0crat** [comment]
Oops! Job `gh:dronmdf/telebot#42` was not in scope
