### ISSUE TITLE
Запуск тестов из setup.py

### ISSUE THREAD

**Issue by DronMDF** [DronMDF/telebot#44]
Вот здесь есть инструкция, как можно кастомизировать setup.py
https://seasonofcode.com/posts/how-to-add-custom-build-steps-and-commands-to-setuppy.html

**Comment by 0crat** [comment]
There is an unrecoverablefailure on my side. Please, submit it [here](https://github.com/zerocracy/datum):

```
java.lang.IllegalArgumentException: 2 error(s) in XML document: -1:-1: cvc-pattern-valid: Value 'DronMDF' is not facet-valid with respect to pattern '[a-z0-9\-]{3,}' for type 'login'.;-1:-1: cvc-type.3.1.3: The value 'DronMDF' of element 'author' is not valid.
	at com.jcabi.xml.StrictXML.<init>(StrictXML.java:124)
	at com.jcabi.xml.StrictXML.<init>(StrictXML.java:95)
	at com.jcabi.xml.StrictXML.<init>(StrictXML.java:86)
	at com.zerocracy.Xocument.modify(Xocument.java:233)
	at com.zerocracy.pm.Claims.add(Claims.java:76)
	at com.zerocracy.pm.ClaimOut.postTo(ClaimOut.java:83)
	at com.zerocracy.radars.github.RbOnAssign.react(RbOnAssign.java:70)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbSafe.lambda$react$0(RbSafe.java:63)
	at org.cactoos.func.FuncWithFallback.apply(FuncWithFallback.java:299)
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:66)
	at...
```

**Comment by 0crat** [comment]
Oops! Job `gh:dronmdf/telebot#44` was not in scope
