### ISSUE TITLE
Добавить шаблонов для источников и получателей

### ISSUE THREAD

**Issue by DronMDF** [DronMDF/telebot#47]

**Comment by 0crat** [comment]
There is an unrecoverablefailure on my side. Please, submit it [here](https://github.com/zerocracy/datum):

```
java.lang.IllegalArgumentException: 2 error(s) in XML document: -1:-1: cvc-pattern-valid: Value 'DronMDF' is not facet-valid with respect to pattern '[a-z0-9\-]{3,}' for type 'login'.;-1:-1: cvc-type.3.1.3: The value 'DronMDF' of element 'author' is not valid.
	at com.jcabi.xml.StrictXML.<init>(StrictXML.java:124)
	at com.jcabi.xml.StrictXML.<init>(StrictXML.java:95)
	at com.jcabi.xml.StrictXML.<init>(StrictXML.java:86)
	at com.zerocracy.Xocument.modify(Xocument.java:233)
	at com.zerocracy.pm.Claims.add(Claims.java:76)
	at com.zerocracy.pm.ClaimOut.postTo(ClaimOut.java:83)
	at com.zerocracy.radars.github.RbOnAssign.react(RbOnAssign.java:70)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbSafe.lambda$react$0(RbSafe.java:63)
	at org.cactoos.func.FuncWithFallback.apply(FuncWithFallback.java:299)
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:66)
	at...
```

**Comment by 0crat** [comment]
Oops! Job `gh:dronmdf/telebot#47` was not in scope

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/datum): 

```
 java.lang.IllegalArgumentException: 2 error(s) in XML document: -1:-1: cvc-pattern-valid: Value 'DronMDF' is not facet-valid with respect to pattern '[a-z0-9\-]{3,}' for type 'login'.;-1:-1: cvc-type.3.1.3: The value 'DronMDF' of element 'author' is not valid.
	at com.jcabi.xml.StrictXML.<init>(StrictXML.java:124)
	at com.jcabi.xml.StrictXML.<init>(StrictXML.java:95)
	at com.jcabi.xml.StrictXML.<init>(StrictXML.java:86)
	at com.zerocracy.Xocument.modify(Xocument.java:233)
	at com.zerocracy.pm.Claims.add(Claims.java:76)
	at com.zerocracy.pm.ClaimOut.postTo(ClaimOut.java:83)
	at com.zerocracy.radars.github.RbOnAssign.react(RbOnAssign.java:70)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbSafe.lambda$react$0(RbSafe.java:64)
	at org.cactoos.func.FuncWithFallback.apply(FuncWithFallback.java:299)
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:66)
	at... 
```

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/datum): 

```
 java.lang.IllegalArgumentException: 2 error(s) in XML document: -1:-1: cvc-pattern-valid: Value 'DronMDF' is not facet-valid with respect to pattern '[a-z0-9\-]{3,}' for type 'login'.;-1:-1: cvc-type.3.1.3: The value 'DronMDF' of element 'author' is not valid.
	at com.jcabi.xml.StrictXML.<init>(StrictXML.java:124)
	at com.jcabi.xml.StrictXML.<init>(StrictXML.java:95)
	at com.jcabi.xml.StrictXML.<init>(StrictXML.java:86)
	at com.zerocracy.Xocument.modify(Xocument.java:233)
	at com.zerocracy.pm.Claims.add(Claims.java:76)
	at com.zerocracy.pm.ClaimOut.postTo(ClaimOut.java:83)
	at com.zerocracy.radars.github.RbOnAssign.react(RbOnAssign.java:70)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbSafe.lambda$react$0(RbSafe.java:64)
	at org.cactoos.func.FuncWithFallback.apply(FuncWithFallback.java:299)
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:66)
	at... 
```

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/datum): 

```
 java.lang.IllegalArgumentException: 2 error(s) in XML document: -1:-1: cvc-pattern-valid: Value 'DronMDF' is not facet-valid with respect to pattern '[a-z0-9\-]{3,}' for type 'login'.;-1:-1: cvc-type.3.1.3: The value 'DronMDF' of element 'author' is not valid.
	at com.jcabi.xml.StrictXML.<init>(StrictXML.java:124)
	at com.jcabi.xml.StrictXML.<init>(StrictXML.java:95)
	at com.jcabi.xml.StrictXML.<init>(StrictXML.java:86)
	at com.zerocracy.Xocument.modify(Xocument.java:233)
	at com.zerocracy.pm.Claims.add(Claims.java:76)
	at com.zerocracy.pm.ClaimOut.postTo(ClaimOut.java:83)
	at com.zerocracy.radars.github.RbOnAssign.react(RbOnAssign.java:70)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbSafe.lambda$react$0(RbSafe.java:64)
	at org.cactoos.func.FuncWithFallback.apply(FuncWithFallback.java:299)
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:66)
	at... 
```

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/datum): 

```
 java.lang.IllegalArgumentException: 2 error(s) in XML document: -1:-1: cvc-pattern-valid: Value 'DronMDF' is not facet-valid with respect to pattern '[a-z0-9\-]{3,}' for type 'login'.;-1:-1: cvc-type.3.1.3: The value 'DronMDF' of element 'author' is not valid.
	at com.jcabi.xml.StrictXML.<init>(StrictXML.java:124)
	at com.jcabi.xml.StrictXML.<init>(StrictXML.java:95)
	at com.jcabi.xml.StrictXML.<init>(StrictXML.java:86)
	at com.zerocracy.Xocument.modify(Xocument.java:233)
	at com.zerocracy.pm.Claims.add(Claims.java:76)
	at com.zerocracy.pm.ClaimOut.postTo(ClaimOut.java:83)
	at com.zerocracy.radars.github.RbOnAssign.react(RbOnAssign.java:70)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbSafe.lambda$react$0(RbSafe.java:64)
	at org.cactoos.func.FuncWithFallback.apply(FuncWithFallback.java:299)
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:66)
	at... 
```

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/datum): 

```
 java.lang.IllegalArgumentException: 2 error(s) in XML document: -1:-1: cvc-pattern-valid: Value 'DronMDF' is not facet-valid with respect to pattern '[a-z0-9\-]{3,}' for type 'login'.;-1:-1: cvc-type.3.1.3: The value 'DronMDF' of element 'author' is not valid.
	at com.jcabi.xml.StrictXML.<init>(StrictXML.java:124)
	at com.jcabi.xml.StrictXML.<init>(StrictXML.java:95)
	at com.jcabi.xml.StrictXML.<init>(StrictXML.java:86)
	at com.zerocracy.Xocument.modify(Xocument.java:233)
	at com.zerocracy.pm.Claims.add(Claims.java:76)
	at com.zerocracy.pm.ClaimOut.postTo(ClaimOut.java:83)
	at com.zerocracy.radars.github.RbOnAssign.react(RbOnAssign.java:70)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbSafe.lambda$react$0(RbSafe.java:64)
	at org.cactoos.func.FuncWithFallback.apply(FuncWithFallback.java:299)
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:66)
	at... 
```

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/datum): 

```
 java.lang.IllegalArgumentException: 2 error(s) in XML document: -1:-1: cvc-pattern-valid: Value 'DronMDF' is not facet-valid with respect to pattern '[a-z0-9\-]{3,}' for type 'login'.;-1:-1: cvc-type.3.1.3: The value 'DronMDF' of element 'author' is not valid.
	at com.jcabi.xml.StrictXML.<init>(StrictXML.java:124)
	at com.jcabi.xml.StrictXML.<init>(StrictXML.java:95)
	at com.jcabi.xml.StrictXML.<init>(StrictXML.java:86)
	at com.zerocracy.Xocument.modify(Xocument.java:233)
	at com.zerocracy.pm.Claims.add(Claims.java:76)
	at com.zerocracy.pm.ClaimOut.postTo(ClaimOut.java:83)
	at com.zerocracy.radars.github.RbOnAssign.react(RbOnAssign.java:70)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbSafe.lambda$react$0(RbSafe.java:64)
	at org.cactoos.func.FuncWithFallback.apply(FuncWithFallback.java:299)
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:66)
	at... 
```

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/datum): 

```
 java.lang.IllegalArgumentException: 2 error(s) in XML document: -1:-1: cvc-pattern-valid: Value 'DronMDF' is not facet-valid with respect to pattern '[a-z0-9\-]{3,}' for type 'login'.;-1:-1: cvc-type.3.1.3: The value 'DronMDF' of element 'author' is not valid.
	at com.jcabi.xml.StrictXML.<init>(StrictXML.java:124)
	at com.jcabi.xml.StrictXML.<init>(StrictXML.java:95)
	at com.jcabi.xml.StrictXML.<init>(StrictXML.java:86)
	at com.zerocracy.Xocument.modify(Xocument.java:233)
	at com.zerocracy.pm.Claims.add(Claims.java:76)
	at com.zerocracy.pm.ClaimOut.postTo(ClaimOut.java:83)
	at com.zerocracy.radars.github.RbOnAssign.react(RbOnAssign.java:70)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbSafe.lambda$react$0(RbSafe.java:64)
	at org.cactoos.func.FuncWithFallback.apply(FuncWithFallback.java:299)
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:66)
	at... 
```

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/datum): 

```
 java.lang.IllegalArgumentException: 2 error(s) in XML document: -1:-1: cvc-pattern-valid: Value 'DronMDF' is not facet-valid with respect to pattern '[a-z0-9\-]{3,}' for type 'login'.;-1:-1: cvc-type.3.1.3: The value 'DronMDF' of element 'author' is not valid.
	at com.jcabi.xml.StrictXML.<init>(StrictXML.java:124)
	at com.jcabi.xml.StrictXML.<init>(StrictXML.java:95)
	at com.jcabi.xml.StrictXML.<init>(StrictXML.java:86)
	at com.zerocracy.Xocument.modify(Xocument.java:233)
	at com.zerocracy.pm.Claims.add(Claims.java:76)
	at com.zerocracy.pm.ClaimOut.postTo(ClaimOut.java:83)
	at com.zerocracy.radars.github.RbOnAssign.react(RbOnAssign.java:70)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbSafe.lambda$react$0(RbSafe.java:64)
	at org.cactoos.func.FuncWithFallback.apply(FuncWithFallback.java:299)
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:66)
	at... 
```

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/datum): 

```
 java.lang.IllegalArgumentException: 2 error(s) in XML document: -1:-1: cvc-pattern-valid: Value 'DronMDF' is not facet-valid with respect to pattern '[a-z0-9\-]{3,}' for type 'login'.;-1:-1: cvc-type.3.1.3: The value 'DronMDF' of element 'author' is not valid.
	at com.jcabi.xml.StrictXML.<init>(StrictXML.java:124)
	at com.jcabi.xml.StrictXML.<init>(StrictXML.java:95)
	at com.jcabi.xml.StrictXML.<init>(StrictXML.java:86)
	at com.zerocracy.Xocument.modify(Xocument.java:233)
	at com.zerocracy.pm.Claims.add(Claims.java:76)
	at com.zerocracy.pm.ClaimOut.postTo(ClaimOut.java:83)
	at com.zerocracy.radars.github.RbOnAssign.react(RbOnAssign.java:70)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbSafe.lambda$react$0(RbSafe.java:64)
	at org.cactoos.func.FuncWithFallback.apply(FuncWithFallback.java:299)
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:66)
	at... 
```

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/datum): 

```
 java.lang.IllegalArgumentException: 2 error(s) in XML document: -1:-1: cvc-pattern-valid: Value 'DronMDF' is not facet-valid with respect to pattern '[a-z0-9\-]{3,}' for type 'login'.;-1:-1: cvc-type.3.1.3: The value 'DronMDF' of element 'author' is not valid.
	at com.jcabi.xml.StrictXML.<init>(StrictXML.java:124)
	at com.jcabi.xml.StrictXML.<init>(StrictXML.java:95)
	at com.jcabi.xml.StrictXML.<init>(StrictXML.java:86)
	at com.zerocracy.Xocument.modify(Xocument.java:233)
	at com.zerocracy.pm.Claims.add(Claims.java:76)
	at com.zerocracy.pm.ClaimOut.postTo(ClaimOut.java:83)
	at com.zerocracy.radars.github.RbOnAssign.react(RbOnAssign.java:70)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbSafe.lambda$react$0(RbSafe.java:64)
	at org.cactoos.func.FuncWithFallback.apply(FuncWithFallback.java:299)
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:66)
	at... 
```

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/datum): 

```
 java.lang.IllegalArgumentException: 2 error(s) in XML document: -1:-1: cvc-pattern-valid: Value 'DronMDF' is not facet-valid with respect to pattern '[a-z0-9\-]{3,}' for type 'login'.;-1:-1: cvc-type.3.1.3: The value 'DronMDF' of element 'author' is not valid.
	at com.jcabi.xml.StrictXML.<init>(StrictXML.java:124)
	at com.jcabi.xml.StrictXML.<init>(StrictXML.java:95)
	at com.jcabi.xml.StrictXML.<init>(StrictXML.java:86)
	at com.zerocracy.Xocument.modify(Xocument.java:233)
	at com.zerocracy.pm.Claims.add(Claims.java:76)
	at com.zerocracy.pm.ClaimOut.postTo(ClaimOut.java:83)
	at com.zerocracy.radars.github.RbOnAssign.react(RbOnAssign.java:70)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbSafe.lambda$react$0(RbSafe.java:64)
	at org.cactoos.func.FuncWithFallback.apply(FuncWithFallback.java:299)
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:66)
	at... 
```

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/datum): 

```
 java.lang.IllegalArgumentException: 2 error(s) in XML document: -1:-1: cvc-pattern-valid: Value 'DronMDF' is not facet-valid with respect to pattern '[a-z0-9\-]{3,}' for type 'login'.;-1:-1: cvc-type.3.1.3: The value 'DronMDF' of element 'author' is not valid.
	at com.jcabi.xml.StrictXML.<init>(StrictXML.java:124)
	at com.jcabi.xml.StrictXML.<init>(StrictXML.java:95)
	at com.jcabi.xml.StrictXML.<init>(StrictXML.java:86)
	at com.zerocracy.Xocument.modify(Xocument.java:233)
	at com.zerocracy.pm.Claims.add(Claims.java:76)
	at com.zerocracy.pm.ClaimOut.postTo(ClaimOut.java:83)
	at com.zerocracy.radars.github.RbOnAssign.react(RbOnAssign.java:70)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbSafe.lambda$react$0(RbSafe.java:64)
	at org.cactoos.func.FuncWithFallback.apply(FuncWithFallback.java:299)
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:66)
	at... 
```

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/datum): 

```
 java.lang.IllegalArgumentException: 2 error(s) in XML document: -1:-1: cvc-pattern-valid: Value 'DronMDF' is not facet-valid with respect to pattern '[a-z0-9\-]{3,}' for type 'login'.;-1:-1: cvc-type.3.1.3: The value 'DronMDF' of element 'author' is not valid.
	at com.jcabi.xml.StrictXML.<init>(StrictXML.java:124)
	at com.jcabi.xml.StrictXML.<init>(StrictXML.java:95)
	at com.jcabi.xml.StrictXML.<init>(StrictXML.java:86)
	at com.zerocracy.Xocument.modify(Xocument.java:233)
	at com.zerocracy.pm.Claims.add(Claims.java:76)
	at com.zerocracy.pm.ClaimOut.postTo(ClaimOut.java:83)
	at com.zerocracy.radars.github.RbOnAssign.react(RbOnAssign.java:70)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbSafe.lambda$react$0(RbSafe.java:64)
	at org.cactoos.func.FuncWithFallback.apply(FuncWithFallback.java:299)
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:66)
	at... 
```

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/datum): 

```
 java.lang.IllegalArgumentException: 2 error(s) in XML document: -1:-1: cvc-pattern-valid: Value 'DronMDF' is not facet-valid with respect to pattern '[a-z0-9\-]{3,}' for type 'login'.;-1:-1: cvc-type.3.1.3: The value 'DronMDF' of element 'author' is not valid.
	at com.jcabi.xml.StrictXML.<init>(StrictXML.java:124)
	at com.jcabi.xml.StrictXML.<init>(StrictXML.java:95)
	at com.jcabi.xml.StrictXML.<init>(StrictXML.java:86)
	at com.zerocracy.Xocument.modify(Xocument.java:233)
	at com.zerocracy.pm.Claims.add(Claims.java:76)
	at com.zerocracy.pm.ClaimOut.postTo(ClaimOut.java:83)
	at com.zerocracy.radars.github.RbOnAssign.react(RbOnAssign.java:70)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbSafe.lambda$react$0(RbSafe.java:64)
	at org.cactoos.func.FuncWithFallback.apply(FuncWithFallback.java:299)
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:66)
	at... 
```

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/datum): 

```
 java.lang.IllegalArgumentException: 2 error(s) in XML document: -1:-1: cvc-pattern-valid: Value 'DronMDF' is not facet-valid with respect to pattern '[a-z0-9\-]{3,}' for type 'login'.;-1:-1: cvc-type.3.1.3: The value 'DronMDF' of element 'author' is not valid.
	at com.jcabi.xml.StrictXML.<init>(StrictXML.java:124)
	at com.jcabi.xml.StrictXML.<init>(StrictXML.java:95)
	at com.jcabi.xml.StrictXML.<init>(StrictXML.java:86)
	at com.zerocracy.Xocument.modify(Xocument.java:233)
	at com.zerocracy.pm.Claims.add(Claims.java:76)
	at com.zerocracy.pm.ClaimOut.postTo(ClaimOut.java:83)
	at com.zerocracy.radars.github.RbOnAssign.react(RbOnAssign.java:70)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbSafe.lambda$react$0(RbSafe.java:64)
	at org.cactoos.func.FuncWithFallback.apply(FuncWithFallback.java:299)
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:66)
	at... 
```

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/datum): 

```
 java.lang.IllegalArgumentException: 2 error(s) in XML document: -1:-1: cvc-pattern-valid: Value 'DronMDF' is not facet-valid with respect to pattern '[a-z0-9\-]{3,}' for type 'login'.;-1:-1: cvc-type.3.1.3: The value 'DronMDF' of element 'author' is not valid.
	at com.jcabi.xml.StrictXML.<init>(StrictXML.java:124)
	at com.jcabi.xml.StrictXML.<init>(StrictXML.java:95)
	at com.jcabi.xml.StrictXML.<init>(StrictXML.java:86)
	at com.zerocracy.Xocument.modify(Xocument.java:233)
	at com.zerocracy.pm.Claims.add(Claims.java:76)
	at com.zerocracy.pm.ClaimOut.postTo(ClaimOut.java:83)
	at com.zerocracy.radars.github.RbOnAssign.react(RbOnAssign.java:70)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbSafe.lambda$react$0(RbSafe.java:64)
	at org.cactoos.func.FuncWithFallback.apply(FuncWithFallback.java:299)
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:66)
	at... 
```

**Comment by DronMDF** [comment]
@yegor256 Здесь видимо возникла какая-то проблема... :(

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/datum): 

```
 java.lang.IllegalArgumentException: 2 error(s) in XML document: -1:-1: cvc-pattern-valid: Value 'DronMDF' is not facet-valid with respect to pattern '[a-z0-9\-]{3,}' for type 'login'.;-1:-1: cvc-type.3.1.3: The value 'DronMDF' of element 'author' is not valid.
	at com.jcabi.xml.StrictXML.<init>(StrictXML.java:124)
	at com.jcabi.xml.StrictXML.<init>(StrictXML.java:95)
	at com.jcabi.xml.StrictXML.<init>(StrictXML.java:86)
	at com.zerocracy.Xocument.modify(Xocument.java:233)
	at com.zerocracy.pm.Claims.add(Claims.java:76)
	at com.zerocracy.pm.ClaimOut.postTo(ClaimOut.java:83)
	at com.zerocracy.radars.github.RbOnAssign.react(RbOnAssign.java:70)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbSafe.lambda$react$0(RbSafe.java:64)
	at org.cactoos.func.FuncWithFallback.apply(FuncWithFallback.java:299)
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:66)
	at... 
```

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/datum): 

```
 java.lang.IllegalArgumentException: 2 error(s) in XML document: -1:-1: cvc-pattern-valid: Value 'DronMDF' is not facet-valid with respect to pattern '[a-z0-9\-]{3,}' for type 'login'.;-1:-1: cvc-type.3.1.3: The value 'DronMDF' of element 'author' is not valid.
	at com.jcabi.xml.StrictXML.<init>(StrictXML.java:124)
	at com.jcabi.xml.StrictXML.<init>(StrictXML.java:95)
	at com.jcabi.xml.StrictXML.<init>(StrictXML.java:86)
	at com.zerocracy.Xocument.modify(Xocument.java:233)
	at com.zerocracy.pm.Claims.add(Claims.java:76)
	at com.zerocracy.pm.ClaimOut.postTo(ClaimOut.java:83)
	at com.zerocracy.radars.github.RbOnAssign.react(RbOnAssign.java:70)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbSafe.lambda$react$0(RbSafe.java:64)
	at org.cactoos.func.FuncWithFallback.apply(FuncWithFallback.java:299)
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:66)
	at... 
```

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/datum): 

```
 java.lang.IllegalArgumentException: 2 error(s) in XML document: -1:-1: cvc-pattern-valid: Value 'DronMDF' is not facet-valid with respect to pattern '[a-z0-9\-]{3,}' for type 'login'.;-1:-1: cvc-type.3.1.3: The value 'DronMDF' of element 'author' is not valid.
	at com.jcabi.xml.StrictXML.<init>(StrictXML.java:124)
	at com.jcabi.xml.StrictXML.<init>(StrictXML.java:95)
	at com.jcabi.xml.StrictXML.<init>(StrictXML.java:86)
	at com.zerocracy.Xocument.modify(Xocument.java:233)
	at com.zerocracy.pm.Claims.add(Claims.java:76)
	at com.zerocracy.pm.ClaimOut.postTo(ClaimOut.java:83)
	at com.zerocracy.radars.github.RbOnAssign.react(RbOnAssign.java:70)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbSafe.lambda$react$0(RbSafe.java:64)
	at org.cactoos.func.FuncWithFallback.apply(FuncWithFallback.java:299)
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:66)
	at... 
```

**Comment by yegor256** [comment]
@DronMDF починили

**Comment by DronMDF** [comment]
@yegor256 Thank's

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see par.19: -5 points just awarded to @dronmdf, total is [+585](http://www.0crat.com/u/dronmdf).

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#47` assigned to @dronmdf, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
Oops! Job `gh:dronmdf/telebot#47` is already assigned to @dronmdf, sorry.

**Comment by 0crat** [comment]
Bug was reported: +15 points just awarded to @dronmdf, total is [+600](http://www.0crat.com/u/dronmdf).

**Comment by 0crat** [comment]
@dronmdf this job was assigned to you 8 days ago.
It will be taken away from you after 10 days from start (this is our policy).

**Comment by 0crat** [comment]
@dronmdf resigned from `gh:dronmdf/telebot#47`, please stop working.

**Comment by 0crat** [comment]
Oops! Job `gh:dronmdf/telebot#47` is not assigned to anyone.

**Comment by 0crat** [comment]
Oops! Job `gh:dronmdf/telebot#47` is not assigned to anyone.

**Comment by DronMDF** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/DronMDF/telebot/issues/47#issuecomment-346135563))

@DronMDF Job `gh:dronmdf/telebot#47` assigned to @dronmdf, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by DronMDF** [comment]
@0crat out

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see par.19: -5 points just awarded to @dronmdf, total is [+785](http://www.0crat.com/u/dronmdf).

**Comment by 0crat** [comment]
Oops! You need to have one of these roles in order to do what you're trying to do: ARC, PO. I'm sorry to say this, but at the moment you've got no roles in this project (your GitHub login is "0crat").

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/DronMDF/telebot/issues/47#issuecomment-346136202))

@DronMDF @dronmdf resigned from `gh:dronmdf/telebot#47`, since the job is not in scope anymore.

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/DronMDF/telebot/issues/47#issuecomment-346136202))

@DronMDF Job `gh:dronmdf/telebot#47` is now out of scope.

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/DronMDF/telebot/issues/47#issuecomment-346136202))

@DronMDF Oops! Job `gh:dronmdf/telebot#47` is not in scope.
