### ISSUE TITLE
Добавить контроль mi и cc с помощью radon

### ISSUE THREAD

**Issue by DronMDF** [DronMDF/telebot#52]

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/datum): 

```
 java.lang.AssertionError: HTTP response status is not equal to 200:
404 Not Found [https://api.github.com/repos/DronMDF/telebot/issues/52]
Server: GitHub.com
Date: Thu, 19 Oct 2017 20:45:36 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Status: 404 Not Found
X-RateLimit-Limit: 5000
X-RateLimit-Remaining: 4999
X-RateLimit-Reset: 1508449535
X-GitHub-Media-Type: github.v3
Access-Control-Expose-Headers: ETag, Link, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval
Access-Control-Allow-Origin: *
Expect-CT: max-age=2592000; report-uri="https://api.github.com/_private/browser/errors"
Content-Security-Policy: default-src 'none'
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-Runtime-Rack: 0.052340
X-GitHub-Request-Id: A999:1DFB:76ED6D:118FD48:59E90EEF

{"message":"Not Fo... 
```

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#52` assigned to @dronmdf, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/datum): 

```
 java.lang.IllegalStateException: event of type 'closed' not found in issue #52
	at com.jcabi.github.Issue$Smart.latestEvent_aroundBody40(Issue.java:365)
	at com.jcabi.github.Issue$Smart$AjcClosure41.run(Issue.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:213)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:140)
	at com.jcabi.github.Issue$Smart.latestEvent(Issue.java:354)
	at com.zerocracy.radars.github.RbVerifyCloser.closer(RbVerifyCloser.java:83)
	at com.zerocracy.radars.github.RbVerifyCloser.react(RbVerifyCloser.java:47)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound$Chain.react(Re... 
```

**Comment by 0crat** [comment]
Bug was reported: +15 points just awarded to @dronmdf, total is [+625](http://www.0crat.com/u/dronmdf).

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see par.19: -5 points just awarded to @dronmdf, total is [+625](http://www.0crat.com/u/dronmdf).

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#52` is now out of scope.

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @dronmdf, total is [+655](http://www.0crat.com/u/dronmdf).
