### ISSUE TITLE
Написать сервер

### ISSUE THREAD

**Issue by DronMDF** [DronMDF/telebot#6]

**Comment by DronMDF** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/DronMDF/telebot/issues/6#issuecomment-330656102))

@DronMDF Job `gh:dronmdf/telebot#6` is in scope.

**Comment by 0crat** [comment]
+15 points just awarded to @dronmdf, total is [+90](http://www.0crat.com/u/dronmdf).

**Comment by DronMDF** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/DronMDF/telebot/issues/6#issuecomment-332945566))

@DronMDF Oops! Job `gh:dronmdf/telebot#6` is not assigned, can't get performer

**Comment by DronMDF** [comment]
@0crat out

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/datum):

```
java.io.IOException: java.lang.IllegalStateException: Failed to acquire "PMO/people.xml" in 20s
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:74)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:60)
	at com.zerocracy.farm.UplinkedProject.acq(UplinkedProject.java:100)
	at com.zerocracy.farm.reactive.RvProject.acq(RvProject.java:61)
	at com.zerocracy.farm.ruled.RdProject.acq(RdProject.java:54)
	at com.zerocracy.pmo.Pmo.acq(Pmo.java:53)
	at com.zerocracy.pmo.People.item(People.java:371)
	at com.zerocracy.pmo.People.bootstrap(People.java:71)
	at com.zerocracy.radars.github.Author.login(Author.java:61)
	at com.zerocracy.radars.github.ReQuestion.react(ReQuestion.java:58)
	at com.zerocracy.radars.github.ReIfAddressed.react(ReIfAddressed.java:58)
	at com.zerocracy.radars.github.ReNotMine.react(ReNotMine.java:55)
	at com.zerocracy.radars.github.ReSafe.lambda$react$0(ReSafe.java:61)
	at org.cactoos.func.FuncWithFallback.apply(FuncWithFallback.java:299)
	at org.c...
```

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#6` assigned to @paddox, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by DronMDF** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/DronMDF/telebot/issues/6#issuecomment-333234570))

@DronMDF @paddox resigned from `gh:dronmdf/telebot#6`, please stop working.

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#6` assigned to @sminux, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by DronMDF** [comment]
Поясню: Это должен быть минимальный запускаемый питоновский бинарник.
Чтобы можно было с консоли тыркнуть ./xxxx и это прошло бы без ошибок.
Внутри нужно написать todo, что делать дальше.
Вот тут есть примеры: http://www.yegor256.com/2009/03/04/pdd.html

**Comment by DronMDF** [comment]
ok

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#6` is now out of scope.

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @sminux, total is [+60](http://www.0crat.com/u/sminux).
