### ISSUE TITLE
Сборка под cmake

### ISSUE THREAD

**Issue by DronMDF** [DronMDF/telebot#7]

**Comment by DronMDF** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/DronMDF/telebot/issues/7#issuecomment-330656194))

@DronMDF Job `gh:dronmdf/telebot#7` is in scope.

**Comment by 0crat** [comment]
+15 points just awarded to @dronmdf, total is [+105](http://www.0crat.com/u/dronmdf).

**Comment by DronMDF** [comment]
@0crat out

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/datum):

```
java.io.IOException: java.lang.IllegalStateException: Failed to acquire "PMO/people.xml" in 20s
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:74)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:60)
	at com.zerocracy.farm.UplinkedProject.acq(UplinkedProject.java:100)
	at com.zerocracy.farm.reactive.RvProject.acq(RvProject.java:61)
	at com.zerocracy.farm.ruled.RdProject.acq(RdProject.java:54)
	at com.zerocracy.pmo.Pmo.acq(Pmo.java:53)
	at com.zerocracy.pmo.People.item(People.java:371)
	at com.zerocracy.pmo.People.bootstrap(People.java:71)
	at com.zerocracy.radars.github.Author.login(Author.java:61)
	at com.zerocracy.radars.github.ReQuestion.react(ReQuestion.java:58)
	at com.zerocracy.radars.github.ReIfAddressed.react(ReIfAddressed.java:58)
	at com.zerocracy.radars.github.ReNotMine.react(ReNotMine.java:55)
	at com.zerocracy.radars.github.ReSafe.lambda$react$0(ReSafe.java:61)
	at org.cactoos.func.FuncWithFallback.apply(FuncWithFallback.java:299)
	at org.c...
```

**Comment by DronMDF** [comment]
@0crat out

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/datum):

```
java.io.IOException: java.lang.IllegalStateException: Failed to acquire "PMO/people.xml" in 20s
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:74)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:60)
	at com.zerocracy.farm.UplinkedProject.acq(UplinkedProject.java:100)
	at com.zerocracy.farm.reactive.RvProject.acq(RvProject.java:61)
	at com.zerocracy.farm.ruled.RdProject.acq(RdProject.java:54)
	at com.zerocracy.pmo.Pmo.acq(Pmo.java:53)
	at com.zerocracy.pmo.People.item(People.java:371)
	at com.zerocracy.pmo.People.bootstrap(People.java:71)
	at com.zerocracy.radars.github.Author.login(Author.java:61)
	at com.zerocracy.radars.github.ReQuestion.react(ReQuestion.java:58)
	at com.zerocracy.radars.github.ReIfAddressed.react(ReIfAddressed.java:58)
	at com.zerocracy.radars.github.ReNotMine.react(ReNotMine.java:55)
	at com.zerocracy.radars.github.ReSafe.lambda$react$0(ReSafe.java:61)
	at org.cactoos.func.FuncWithFallback.apply(FuncWithFallback.java:299)
	at org.c...
```

**Comment by DronMDF** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/DronMDF/telebot/issues/7#issuecomment-332863091))

@DronMDF I can't do it for technical reasons, I'm very sorry. If you don't know what to do, submit this error as a ticket [here](https://github.com/zerocracy/datum):

```
0.16.1 4ccd020 2017-09-19T08:13:54
IllegalStateException: java.lang.reflect.InvocationTargetException
java.lang.IllegalStateException: Failed to acquire "2017/08/C6KLDT6QG/elections.xml" in 20s
	at com.zerocracy.farm.sync.SyncItem.acquire(SyncItem.java:119)
	at com.zerocracy.farm.sync.SyncProject.acq(SyncProject.java:133)
	at com.zerocracy.farm.StrictProject.acq(StrictProject.java:110)
	at com.zerocracy.farm.UplinkedProject.lambda$acq$4(UplinkedProject.java:98)
	at org.cactoos.scalar.Ternary.value(Ternary.java:118)
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:66)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:60)
	at com.zerocracy.farm.UplinkedProject.acq(UplinkedProject.java:100)
	at com.zerocracy.pm.staff.Elections.item(Elections.java:264)
	at com.zerocracy.pm.staff.Elections.bootstrap(Elections.java:67)
	at com.zerocracy.pm.staff.Elections$bootstrap.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)...
```

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/DronMDF/telebot/issues/7#issuecomment-332863091))

@DronMDF Job `gh:dronmdf/telebot#7` is now out of scope.

**Comment by 0crat** [comment]
Oops! Job `gh:dronmdf/telebot#7` was not in scope
