### ISSUE TITLE
Непрерывная интеграция с tracis.ci

### ISSUE THREAD

**Issue by DronMDF** [DronMDF/telebot#9]
Сервер непрерывной интеграции https://travis-ci.org/
К проекту он уже подключен.

**Comment by DronMDF** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/DronMDF/telebot/issues/9#issuecomment-330656359))

@DronMDF Job `gh:dronmdf/telebot#9` is in scope.

**Comment by 0crat** [comment]
+15 points just awarded to @dronmdf, total is [+135](http://www.0crat.com/u/dronmdf).

**Comment by DronMDF** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/DronMDF/telebot/issues/9#issuecomment-332947914))

@DronMDF Oops! Job `gh:dronmdf/telebot#9` is already in scope

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/DronMDF/telebot/issues/9#issuecomment-332947914))

@DronMDF I can't do it for technical reasons, I'm very sorry. If you don't know what to do, submit this error as a ticket [here](https://github.com/zerocracy/datum):

```
0.16.1 4ccd020 2017-09-19T08:13:54
IllegalStateException: java.lang.reflect.InvocationTargetException
java.lang.IllegalStateException: Failed to acquire "2017/08/C6KLDT6QG/elections.xml" in 20s
	at com.zerocracy.farm.sync.SyncItem.acquire(SyncItem.java:119)
	at com.zerocracy.farm.sync.SyncProject.acq(SyncProject.java:133)
	at com.zerocracy.farm.StrictProject.acq(StrictProject.java:110)
	at com.zerocracy.farm.UplinkedProject.lambda$acq$4(UplinkedProject.java:98)
	at org.cactoos.scalar.Ternary.value(Ternary.java:118)
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:66)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:60)
	at com.zerocracy.farm.UplinkedProject.acq(UplinkedProject.java:100)
	at com.zerocracy.pm.staff.Elections.item(Elections.java:264)
	at com.zerocracy.pm.staff.Elections.bootstrap(Elections.java:67)
	at com.zerocracy.pm.staff.Elections$bootstrap.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)...
```

**Comment by DronMDF** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/DronMDF/telebot/issues/9#issuecomment-333064283))

@DronMDF Oops! Job `gh:dronmdf/telebot#9` is already in scope

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/DronMDF/telebot/issues/9#issuecomment-333064283))

@DronMDF I can't do it for technical reasons, I'm very sorry. If you don't know what to do, submit this error as a ticket [here](https://github.com/zerocracy/datum):

```
0.16.1 4ccd020 2017-09-19T08:13:54
IllegalStateException: java.lang.reflect.InvocationTargetException
java.lang.IllegalStateException: Failed to acquire "2017/08/C6KLDT6QG/elections.xml" in 20s
	at com.zerocracy.farm.sync.SyncItem.acquire(SyncItem.java:119)
	at com.zerocracy.farm.sync.SyncProject.acq(SyncProject.java:133)
	at com.zerocracy.farm.StrictProject.acq(StrictProject.java:110)
	at com.zerocracy.farm.UplinkedProject.lambda$acq$4(UplinkedProject.java:98)
	at org.cactoos.scalar.Ternary.value(Ternary.java:118)
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:66)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:60)
	at com.zerocracy.farm.UplinkedProject.acq(UplinkedProject.java:100)
	at com.zerocracy.pm.staff.Elections.item(Elections.java:264)
	at com.zerocracy.pm.staff.Elections.bootstrap(Elections.java:67)
	at com.zerocracy.pm.staff.Elections$bootstrap.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)...
```

**Comment by DronMDF** [comment]
Если посмотреть на список коммитов, там стоят красные кресты.
А должны стоять зеленые галочки.
fix it.

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#9` assigned to @paddox, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by DronMDF** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/DronMDF/telebot/issues/9#issuecomment-333282291))

@DronMDF @paddox resigned from `gh:dronmdf/telebot#9`, please stop working.

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#9` assigned to @talykovnikita, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by DronMDF** [comment]
Если посмотреть в список коммитов, то там сейчас стоят красные кресты.
И по ссылке можно обнаружить подробности.
Которые заключаются в том, что travis не может обнаружить файл .travis.ci в корне проекта.
Если бегло погуглить, то на сайте tracis в докумментации можно найти примеры для питоновских проектов.

**Comment by DronMDF** [comment]
@0crat assign DronMDF

**Comment by 0crat** [comment]
> @0crat assign DronMDF ([here](https://github.com/DronMDF/telebot/issues/9#issuecomment-335501803))

@DronMDF Argument "DronMDF" doesn't match regex "me|@[a-zA-Z0-9\-]+"

**Comment by DronMDF** [comment]
@0crat assign dronmdf

**Comment by DronMDF** [comment]
@0crat assign me

**Comment by 0crat** [comment]
> @0crat assign dronmdf ([here](https://github.com/DronMDF/telebot/issues/9#issuecomment-335511360))

@DronMDF Argument "dronmdf" doesn't match regex "me|@[a-zA-Z0-9\-]+"

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/DronMDF/telebot/issues/9#issuecomment-335511452))

@DronMDF Job `gh:dronmdf/telebot#9` assigned to @dronmdf, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
Oops! You need to have one of these roles in order to do what you're trying to do: ARC, PO. I'm sorry to say this, but at the moment you've got no roles in this project (your GitHub login is "0crat").

**Comment by 0crat** [comment]
Oops! You need to have one of these roles in order to do what you're trying to do: ARC, PO. I'm sorry to say this, but at the moment you've got no roles in this project (your GitHub login is "0crat").

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see par.19: -5 points just awarded to @dronmdf, total is [+390](http://www.0crat.com/u/dronmdf).

**Comment by DronMDF** [comment]
Готово.

**Comment by 0crat** [comment]
Job `gh:dronmdf/telebot#9` is now out of scope.

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @dronmdf, total is [+420](http://www.0crat.com/u/dronmdf).
